// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var points = [
    [
      100,
      100
    ],
    [
      500,
      100
    ],
    [
      500,
      400
    ],
    [
      300,
      400
    ],
    [
      300,
      600
    ],
    [
      1000,
      600
    ],
    [
      1000,
      200
    ],
    [
      200,
      200
    ],
    [
      200,
      100
    ]
  ];
  var box = function (t, l, h, w, c) {
    return JsxRuntime.jsx("div", {
                style: {
                  backgroundColor: c,
                  height: String(h) + "px",
                  left: String(l) + "px",
                  position: "fixed",
                  top: String(t) + "px",
                  width: String(w) + "px"
                }
              });
  };
  var red = "#f87171";
  var blue = "#3730a3";
  return JsxRuntime.jsx("div", {
              children: Core__Array.reduceWithIndex(points, [], (function (arr, cur, i) {
                      var ay = cur[1];
                      var ax = cur[0];
                      var match = points[i + 1 | 0];
                      var match$1 = points[i + 2 | 0];
                      var tmp;
                      if (match !== undefined) {
                        var by = match[1];
                        var bx = match[0];
                        var w = Math.abs(bx - ax | 0) | 0;
                        var h = Math.abs(by - ay | 0) | 0;
                        var horz = i % 2 === 0;
                        var edges = horz ? (
                            bx > ax ? [
                                box(ay, ax, 10, w, red),
                                box(ay - 10 | 0, ax, 10, w, blue)
                              ] : [
                                box(by - 10 | 0, bx, 10, w, red),
                                box(by, bx, 10, w, blue)
                              ]
                          ) : (
                            by > ay ? [
                                box(ay, ax, h, 10, blue),
                                box(ay, ax - 10 | 0, h, 10, red)
                              ] : [
                                box(by, bx - 10 | 0, h, 10, blue),
                                box(by, bx, h, 10, red)
                              ]
                          );
                        var corner;
                        if (match$1 !== undefined) {
                          var match$2 = match$1[0] > ax;
                          var match$3 = match$1[1] > ay;
                          corner = match$2 ? (
                              match$3 ? (
                                  horz ? [box(by - 10 | 0, bx, 10, 10, blue)] : [box(by, bx - 10 | 0, 10, 10, red)]
                                ) : (
                                  horz ? [box(by, bx, 10, 10, red)] : [box(by - 10 | 0, bx - 10 | 0, 10, 10, blue)]
                                )
                            ) : (
                              match$3 ? (
                                  horz ? [box(by - 10 | 0, bx - 10 | 0, 10, 10, red)] : [box(by, bx, 10, 10, blue)]
                                ) : (
                                  horz ? [box(by, bx - 10 | 0, 10, 10, blue)] : [box(by - 10 | 0, bx, 10, 10, red)]
                                )
                            );
                        } else {
                          corner = [];
                        }
                        tmp = edges.concat(corner);
                      } else {
                        tmp = [null];
                      }
                      return arr.concat(tmp);
                    })),
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
